version: "3.9"
services:
  megreat:
    build: .
    entrypoint: "dotnet /app/DBMegreat.ConsoleApp.dll /SQL/config.json"
    volumes:
      - ./test/sql-scripts:/SQL
      - ./test/output:/output
    depends_on:
      - mysql_db
  mysql_db:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db-megreat-test
      MYSQL_USER: test_megreat_user
      MYSQL_PASSWORD: megreat_password
    ports: 
     - 9000:3306
